### Data Analysis with python

- Numpy 
- Pandas

In [1]:
!pip install numpy

In [2]:
## Numpy - Numerical Python

## Numpy is used for creating multi-dimensional arrays and it has functions 

import numpy as np

In [9]:
numbers = np.array([4,5,6,7,8])

In [10]:
print(numbers)

[4 5 6 7 8]


In [11]:
type(numbers)

numpy.ndarray

In [12]:
numbers.ndim

1

In [13]:
arr_2 = np.array([[2, 4], [3, 6]]) 

In [14]:
arr_2.ndim

2

In [15]:
arr_2

array([[2, 4],
       [3, 6]])

In [16]:
arr = np.array([[2, 4, 6], [3, 6]]) 

# homogeneity

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [17]:
arr_3 = np.array([
    [3,4,5],
    [2,7,9],
    [1,7,0]
])

In [18]:
arr_3.ndim

2

In [19]:
arr_3.shape

(3, 3)

In [20]:
arr_2.shape

(2, 2)

In [21]:
# create a 3 * 4 array

arr_4 = np.array([
    [3,4,5,6],
    [2,4,5,6],
    [1,3,4,5]
])

In [22]:
arr_4.shape

(3, 4)

In [23]:
arr_4.ndim

2

In [25]:
arr_5 = np.array([
    [[2,4,5,6], [2,3,4,5]], [[2,6,7,6], [2,3,4,5]]
])

In [26]:
arr_5.shape

(2, 2, 4)

In [27]:
# data type

numbers.dtype

dtype('int32')

In [28]:
names = np.array(['Seun', 'Ola', 'Busayo', 'Onyi', 100])

In [29]:
names

array(['Seun', 'Ola', 'Busayo', 'Onyi', '100'], dtype='<U11')

In [30]:
names.dtype

dtype('<U11')

In [31]:
arr_6 = np.array([45.0, 23.8, 90.4], dtype='float32')

In [32]:
arr_6

array([45. , 23.8, 90.4], dtype=float32)

#### Indexing and Slicing

In [34]:
arr = np.array([3,4,5,6,7,10, 12, 4], dtype='int16')

In [35]:
arr

array([ 3,  4,  5,  6,  7, 10, 12,  4], dtype=int16)

In [36]:
arr[0]

3

In [37]:
arr[-1]

4

In [39]:
arr[:3]

array([3, 4, 5], dtype=int16)

In [40]:
arr_2 = np.array([[2, 4, 5], [3, 6, 6]]) 

In [42]:
arr_2.shape

(2, 3)

In [43]:
arr_2.ndim

2

In [44]:
arr_2

array([[2, 4, 5],
       [3, 6, 6]])

In [45]:
arr_2[0,0]

2

In [46]:
arr_2[1,1]

6

In [47]:
arr_4 = np.array([
    [3,4,5,6],
    [2,4,5,6],
    [1,3,4,5]
])

In [48]:
arr_4[2,2]

4

In [50]:
arr_4[0,1:]

array([4, 5, 6])

In [52]:
arr_4[0:2,0:3]

array([[3, 4, 5],
       [2, 4, 5]])

In [53]:
arr_4[0:2,0:3]

array([[3, 4, 5],
       [2, 4, 5]])

In [60]:
arr_4[2]

array([1, 3, 4, 5])

In [66]:
new_arr = np.concatenate((arr_4[0],arr_4[2])) # flattening

In [70]:
new_arr = new_arr.reshape(4,3) 

In [71]:
new_arr

array([[3, 4],
       [5, 6],
       [1, 3],
       [4, 5]])

In [75]:
numbers = np.array([4,5,6,7,8,9,10,11])

numbers.shape

(8,)

In [78]:
arr = numbers.reshape(2,4)

In [79]:
arr

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
arr.flatten()

array([ 4,  5,  6,  7,  8,  9, 10, 11])

#### Operations

In [81]:
numbers

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
np.sum(numbers)

60

In [83]:
np.mean(numbers)

7.5

In [85]:
std = np.std(numbers)

In [86]:
var = std * 2
var

4.58257569495584

In [87]:
numbers

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [88]:
# vectorize

numbers = numbers + 10

In [89]:
numbers

array([14, 15, 16, 17, 18, 19, 20, 21])

In [92]:
arr1 = np.array([1,2,4,5])
arr2 = np.array([3,4,5,6, 5])

result_arr = arr1 + arr2

result_arr

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [94]:
# filter 

scores = np.array([30, 20, 67, 45, 90, 89, 90])

new_scores = scores[np.where(scores > 45)]
new_scores

array([67, 90, 89, 90])

In [3]:
fruits = np.array(['apple', 'orange', 'banana', 'guava', 'mango'])

[ 'e' not in fruit for fruit in fruits ]
# filter out the fruits where the item contains letter e

[False, False, True, True, True]

In [4]:
new_fruits = fruits[[len(fruit) > 5 for fruit in fruits]]

new_fruits

array(['orange', 'banana'], dtype='<U6')

In [7]:
arr = np.array([3,4,5,6,7])

np.where(arr > 5)

(array([3, 4], dtype=int64),)

In [8]:
arr[np.where(arr > 5)]

array([6, 7])

In [9]:
arr[np.where(arr % 2 == 0)]

array([4, 6])

In [11]:
fruits = np.array(['apple', 'orange', 'banana', 'guava', 'mango'])
# filter out the fruits where the item contains letter e
['e' in fruit for fruit in fruits]

[True, True, False, False, False]

In [12]:
fruits[['e' in fruit for fruit in fruits]]

array(['apple', 'orange'], dtype='<U6')

In [14]:
# filter out the fruits where the length of the item is greater than 5

result = [len(fruit) > 5 for fruit in fruits]
result

[False, True, True, False, False]

In [15]:
fruits[[len(fruit) > 5 for fruit in fruits]]

array(['orange', 'banana'], dtype='<U6')

fruits = np.array(['apple', 'orange', 'banana', 'guava', 'mango'])

Filter out the elements where the first letter is a vowel

scores = np.array([30, 20, 67, 45, 90, 89, 90])

Filter out the elements where the item is an odd number

#### Type Casting

In [16]:
score = np.array([20.4, 24.0, 56.9])

In [17]:
score.dtype

dtype('float64')

In [18]:
score = score.astype('int64')

In [19]:
score.dtype

dtype('int64')

#### Pandas

- Series

- DataFrame

In [20]:
import pandas as pd

C:\Users\aaginam\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [21]:
# Series

# It is an indexed/labeled 1-dim array

student = pd.Series(['Loveth', 'Onyi', 'Fisayo', 'Debby', 'Hamad', 'Fidelis'])

In [22]:
student

0     Loveth
1       Onyi
2     Fisayo
3      Debby
4      Hamad
5    Fidelis
dtype: object

In [23]:
student = pd.Series(['Loveth', 'Onyi', 'Fisayo', 'Debby', 'Hamad', 'Fidelis'], index = ['a', 'b', 'c', 'd', 'e', 'f'])

In [24]:
student

a     Loveth
b       Onyi
c     Fisayo
d      Debby
e      Hamad
f    Fidelis
dtype: object

In [25]:
student['a'] # index

'Loveth'

In [26]:
# slice

student['a':'d']

a    Loveth
b      Onyi
c    Fisayo
d     Debby
dtype: object

In [27]:
ages = pd.Series([45, 34, 23, 12])

In [28]:
ages

0    45
1    34
2    23
3    12
dtype: int64

#### DataFrame

- model of a data stored in a table. It is a 2-dim data structure with rows and columns. A comb of Series

In [30]:
student = pd.Series(['Loveth', 'Onyi', 'Fisayo', 'Debby', 'Hamad', 'Fidelis'])

scores = pd.Series([45, 23, 90, 23, 12, 45])

In [31]:
student

0     Loveth
1       Onyi
2     Fisayo
3      Debby
4      Hamad
5    Fidelis
dtype: object

In [32]:
scores

0    45
1    23
2    90
3    23
4    12
5    45
dtype: int64

In [33]:
data = pd.DataFrame({
    'Student' : student,
    'Scores' : scores
})

In [34]:
data

Student  Scores
0   Loveth      45
1     Onyi      23
2   Fisayo      90
3    Debby      23
4    Hamad      12
5  Fidelis      45

#### Working with real world data

In [52]:
# 1. Read the data

df = pd.read_csv(filepath_or_buffer = 'Data_Sheet_Udemy_Courses_-_Music_Courses - Data_Sheet_Udemy_Courses_-_Music_Courses.csv', sep=',')

In [49]:
df

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

In [38]:
df2 = pd.read_excel('Data_Sheet_Udemy_Courses_-_Music_Courses.xlsx')

In [39]:
df2

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

#### Data Exploration

In [54]:
df.head(3)

course_id                                       course_title  \
0      19421              Free Beginner Electric Guitar Lessons   
1     238934  Pianoforall - Incredible New Way To Learn Pian...   
2      41884                Getting Started with Playing Guitar   

                                                 url  price  num_subscribers  \
0  https://www.udemy.com/beginner-electric-guitar...      0           101154   
1  https://www.udemy.com/pianoforall-incredible-n...    200            75499   
2  https://www.udemy.com/getting-started-with-pla...      0            47652   

   num_reviews  num_lectures           level  Rating  content_duration  \
0         1042            95      All Levels    0.88               4.5   
1         7676           362  Beginner Level    0.96              30.0   
2         1141            26      All Levels    0.68               4.0   

    published_timestamp              subject  
0  2012-06-15T17:00:33Z  Musical Instruments  
1  2014-08-07T06:27:51Z  Musical Instruments  
2  2013-05-29T15:28:07Z  Musical Instruments

In [55]:
df.tail()

course_id                                       course_title  \
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 680 entries, 0 to 679
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_id            680 non-null    int64  
 1   course_title         680 non-null    object 
 2   url                  680 non-null    object 
 3   price                680 non-null    int64  
 4   num_subscribers      680 non-null    int64  
 5   num_reviews          680 non-null    int64  
 6   num_lectures         680 non-null    int64  
 7   level                680 non-null    object 
 8   Rating               680 non-null    float64
 9   content_duration     680 non-null    float64
 10  published_timestamp  680 non-null    object 
 11  subject              680 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 63.9+ KB


In [58]:
df.shape

(680, 12)

In [59]:
df.columns

Index(['course_id', 'course_title', 'url', 'price', 'num_subscribers',
       'num_reviews', 'num_lectures', 'level', 'Rating', 'content_duration',
       'published_timestamp', 'subject'],
      dtype='object')

#### Filtering and Slicing 

In [60]:
df

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

In [61]:
df['url']

0      https://www.udemy.com/beginner-electric-guitar...
1      https://www.udemy.com/pianoforall-incredible-n...
2      https://www.udemy.com/getting-started-with-pla...
3      https://www.udemy.com/complete-guitar-system-b...
4         https://www.udemy.com/learn-guitar-in-21-days/
                             ...                        
675    https://www.udemy.com/learn-to-play-sweet-chil...
676    https://www.udemy.com/coaching-bundle-rhythm-i...
677    https://www.udemy.com/learn-pirates-of-the-car...
678    https://www.udemy.com/learn-to-play-piano-like...
679         https://www.udemy.com/4-week-rhythm-mastery/
Name: url, Length: 680, dtype: object

The operation you can perform on a data is dependent on the dtype

In [62]:
df[['url']]

url
0    https://www.udemy.com/beginner-electric-guitar...
1    https://www.udemy.com/pianoforall-incredible-n...
2    https://www.udemy.com/getting-started-with-pla...
3    https://www.udemy.com/complete-guitar-system-b...
4       https://www.udemy.com/learn-guitar-in-21-days/
..                                                 ...
675  https://www.udemy.com/learn-to-play-sweet-chil...
676  https://www.udemy.com/coaching-bundle-rhythm-i...
677  https://www.udemy.com/learn-pirates-of-the-car...
678  https://www.udemy.com/learn-to-play-piano-like...
679       https://www.udemy.com/4-week-rhythm-mastery/

[680 rows x 1 columns]

In [63]:
df[['course_title']]

course_title
0                Free Beginner Electric Guitar Lessons
1    Pianoforall - Incredible New Way To Learn Pian...
2                  Getting Started with Playing Guitar
3        Complete Guitar System - Beginner to Advanced
4                              Learn Guitar in 21 Days
..                                                 ...
675                  Learn to Play Sweet Child of Mine
676  Coaching Course: Rhythm Instruction for Music ...
677  Learn Pirates of the Caribbean by Ear on the P...
678  Learn to Play Piano Like a Pro - Easy Piano Co...
679                              4 Week Rhythm Mastery

[680 rows x 1 columns]

In [65]:
df[['course_title', 'price']].head(10)

course_title  price
0              Free Beginner Electric Guitar Lessons      0
1  Pianoforall - Incredible New Way To Learn Pian...    200
2                Getting Started with Playing Guitar      0
3      Complete Guitar System - Beginner to Advanced    145
4                            Learn Guitar in 21 Days     20
5                The Professional Guitar Masterclass    200
6              Introduction to Piano - By PGN Piano!      0
7          Best Beginner Guitar Lessons by Sam Lyons     20
8                             Acoustic Guitar Basics      0
9                        Guitar Super System Level 1     50

In [67]:
df[['url', 'price', 'Rating']].tail() 

url  price  Rating
675  https://www.udemy.com/learn-to-play-sweet-chil...     20    0.31
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125    0.06
677  https://www.udemy.com/learn-pirates-of-the-car...     20    0.08
678  https://www.udemy.com/learn-to-play-piano-like...     35    0.78
679       https://www.udemy.com/4-week-rhythm-mastery/     20    0.01

In [68]:
# Label Selection

df

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

In [72]:
df.loc[20:30, ['course_title']]

course_title
20  Acoustic Fingerstyle Guitar Course: Beginner t...
21  PI-101 Top 10 Classical Piano Pieces for Begin...
22  How to play 'Electric Guitar",https://www.udem...
23   Virtual Piano Lessons - A New Way To Learn Piano
24      Guitar Crash Course (No Experience Necessary)
25  Beginner Violin 101: Care, Maintenance, and th...
26  How to play Piano - Go from a Beginner/Interme...
27  Learn to Read & Write Music to play Piano & mo...
28        Play Piano in 30 Days! - Start Playing NOW!
29       The Complete Piano Course - Master The Piano
30       Piano Music Theory (Back To Basics) by JFilt

In [73]:
df.loc[20:30, 'course_id':'price']

course_id                                       course_title  \
20     517148  Acoustic Fingerstyle Guitar Course: Beginner t...   
21     824044  PI-101 Top 10 Classical Piano Pieces for Begin...   
22    1052180  How to play 'Electric Guitar",https://www.udem...   
23      65033   Virtual Piano Lessons - A New Way To Learn Piano   
24     315576      Guitar Crash Course (No Experience Necessary)   
25     364716  Beginner Violin 101: Care, Maintenance, and th...   
26     967380  How to play Piano - Go from a Beginner/Interme...   
27    1032864  Learn to Read & Write Music to play Piano & mo...   
28     555340        Play Piano in 30 Days! - Start Playing NOW!   
29     574974       The Complete Piano Course - Master The Piano   
30    1105794       Piano Music Theory (Back To Basics) by JFilt   

                                                  url  price  
20  https://www.udemy.com/acoustic-fingerstyle-gui...    200  
21                https://www.udemy.com/pi-101-piano/      0  
22             https://www.udemy.com/learnpianotoday/    100  
23  https://www.udemy.com/virtual-piano-lessons-a-...     50  
24     https://www.udemy.com/hub-guitar-crash-course/      0  
25  https://www.udemy.com/beginner-violin-101-care...      0  
26  https://www.udemy.com/how-to-play-piano-go-fro...    200  
27  https://www.udemy.com/the-complete-guide-to-ho...    115  
28                 https://www.udemy.com/flyingstart/      0  
29   https://www.udemy.com/the-complete-piano-course/     95  
30  https://www.udemy.com/piano-music-theory-back-...      0

In [74]:
# iloc - integer labeled

df

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

In [75]:
df.iloc[0:10, 0:2]

course_id                                       course_title
0      19421              Free Beginner Electric Guitar Lessons
1     238934  Pianoforall - Incredible New Way To Learn Pian...
2      41884                Getting Started with Playing Guitar
3      42271      Complete Guitar System - Beginner to Advanced
4      26956                            Learn Guitar in 21 Days
5     456284                The Professional Guitar Masterclass
6     583752              Introduction to Piano - By PGN Piano!
7      59922          Best Beginner Guitar Lessons by Sam Lyons
8     198690                             Acoustic Guitar Basics
9     484670                        Guitar Super System Level 1

In [89]:
df.loc[df['price'] >= 200, ['course_title', 'price', 'Rating']]

course_title  price  Rating
1    Pianoforall - Incredible New Way To Learn Pian...    200    0.96
5                  The Professional Guitar Masterclass    200    0.30
13   LEARN HARMONICA, amaze your friends and have f...    200    0.43
16                Ultimate Beginner Guitar Masterclass    200    0.18
17   Quicklessons Piano Course - Learn to Play Pian...    200    0.15
20   Acoustic Fingerstyle Guitar Course: Beginner t...    200    0.11
26   How to play Piano - Go from a Beginner/Interme...    200    0.14
37   Guitar Chord Mastery!Turn Your Brain Into A Ch...    200    0.14
43   Learn to Play Piano From a Concert Pianist - F...    200    0.11
89         Learn How to Improvise on Guitar in 30 Days    200    0.47
97   Drumming Accelerator: How To Get The Best Star...    200    0.11
108                  The Professional Bass Masterclass    200    0.68
111  101 Blues riffs - learn how the harmonica supe...    200    0.55
198  Play Sonny Terry style on Harmonica and dazzle...    200    0.07
205  Music Fundamentals: Learn Beatmaking with Pen ...    200    0.07
243  Chugging - it don't mean a thing if it ain't g...    200    0.18
282  Bones of the Blues - learn 4 cool tunes to exp...    200    0.02
396                             Beginner Guitar Method    200    0.04
667                                Suonare la Chitarra    200    0.15

In [79]:
df[['price']].describe()

price
count  680.000000
mean    49.558824
std     41.187592
min      0.000000
25%     20.000000
50%     40.000000
75%     50.000000
max    200.000000

In [101]:
df

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

In [102]:
df.loc[:, ['course_id', 'course_title']]

course_id                                       course_title
0        19421              Free Beginner Electric Guitar Lessons
1       238934  Pianoforall - Incredible New Way To Learn Pian...
2        41884                Getting Started with Playing Guitar
3        42271      Complete Guitar System - Beginner to Advanced
4        26956                            Learn Guitar in 21 Days
..         ...                                                ...
675    1216340                  Learn to Play Sweet Child of Mine
676    1026762  Coaching Course: Rhythm Instruction for Music ...
677    1223240  Learn Pirates of the Caribbean by Ear on the P...
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...
679    1234656                              4 Week Rhythm Mastery

[680 rows x 2 columns]

In [105]:
df.iloc[:, [0,1]]

course_id                                       course_title
0        19421              Free Beginner Electric Guitar Lessons
1       238934  Pianoforall - Incredible New Way To Learn Pian...
2        41884                Getting Started with Playing Guitar
3        42271      Complete Guitar System - Beginner to Advanced
4        26956                            Learn Guitar in 21 Days
..         ...                                                ...
675    1216340                  Learn to Play Sweet Child of Mine
676    1026762  Coaching Course: Rhythm Instruction for Music ...
677    1223240  Learn Pirates of the Caribbean by Ear on the P...
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...
679    1234656                              4 Week Rhythm Mastery

[680 rows x 2 columns]

In [106]:
df

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

Filter the dataframe and return the rows where the level is beginner level and all the columns from course_id to level

In [107]:
df.loc[df.level == 'Beginner Level','course_id':'level']

course_id                                       course_title  \
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
8       198690                             Acoustic Guitar Basics   
13      200598  LEARN HARMONICA, amaze your friends and have f...   
15       99324                      Acoustic Blues Guitar Lessons   
21      824044  PI-101 Top 10 Classical Piano Pieces for Begin...   
..         ...                                                ...   
669    1265814  ABRSM Grade III Piano Class - Handel Sonatina ...   
671     603902             Curso de Didgeridoo nivel principiante   
673    1214670                  Tune that Sour Note on Your Piano   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   

                                                   url  price  \
1    https://www.udemy.com/pianoforall-incredible-n...    200   
8        https://www.udemy.com/acoustic-guitar-basics/      0   
13   https://www.udemy.com/benhewlettharmonicatuiti...    200   
15   https://www.udemy.com/finger-picking-blues-gui...      0   
21                 https://www.udemy.com/pi-101-piano/      0   
..                                                 ...    ...   
669  https://www.udemy.com/abrsm-grade-iii-piano-cl...     20   
671  https://www.udemy.com/curso-de-didgeridoo-nive...     50   
673  https://www.udemy.com/how-to-tune-your-own-piano/     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
678  https://www.udemy.com/learn-to-play-piano-like...     35   

     num_subscribers  num_reviews  num_lectures           level  
1              75499         7676           362  Beginner Level  
8              14495          224            21  Beginner Level  
13              8857          718           131  Beginner Level  
15              8217          109            10  Beginner Level  
21              6292          183            38  Beginner Level  
..               ...          ...           ...             ...  
669                0            0             5  Beginner Level  
671                0            0            31  Beginner Level  
673                0            0             6  Beginner Level  
676                0            0             7  Beginner Level  
678                0            0            13  Beginner Level  

[266 rows x 8 columns]

Filter the dataframe and return the rows where the level is all level and the rating is greater and equal to 0.5

In [120]:
df.loc[df.level == 'All Levels'][df.Rating > 0.5]

C:\Users\aaginam\AppData\Local\Temp\ipykernel_26280\1233354856.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df.loc[df.level == 'All Levels'][df.Rating > 0.5]


course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
14      101496  How To Play Blues Guitar - Broonzy & McGhee Bl...   
78     1123184  #7 Piano Hand Coordination: Play Piano Runs in...   
..         ...                                                ...   
658     834422                                   Curso de Teclado   
660     968026             Learn to Play Tabla - The Indian drums   
670    1272282      Learn Vikings Soundtracks on the Piano by Ear   
672    1026760  Coaching Course: Rhythm Instruction for Music ...   
674     993892  Beginners Guitar Course - 'Try it and love it ...   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
14   https://www.udemy.com/swing-acoustic-blues-gui...      0   
78   https://www.udemy.com/learn-piano-hand-coordin...     65   
..                                                 ...    ...   
658  https://www.udemy.com/curso-de-teclado-gospel-...     40   
660         https://www.udemy.com/learn-to-play-tabla/      0   
670  https://www.udemy.com/learn-vikings-soundtrack...     20   
672  https://www.udemy.com/coaching-bundle-rhythm-i...    130   
674  https://www.udemy.com/beginners-guitar-course-...     25   

     num_subscribers  num_reviews  num_lectures       level  Rating  \
0             101154         1042            95  All Levels    0.88   
2              47652         1141            26  All Levels    0.68   
3              32935         2713           310  All Levels    0.65   
14              8240           31             6  All Levels    0.52   
78              2015            2            25  All Levels    0.95   
..               ...          ...           ...         ...     ...   
658                1            0            26  All Levels    0.96   
660                1            0            20  All Levels    0.78   
670                0            0             8  All Levels    0.63   
672                0            0             6  All Levels    0.66   
674                0            0            16  All Levels    0.51   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
14           1.500000  2013-11-23T12:27:56Z  Musical Instruments  
78           1.000000  2017-03-08T18:09:32Z  Musical Instruments  
..                ...                   ...                  ...  
658          1.500000  2016-05-16T18:46:15Z  Musical Instruments  
660          1.500000  2017-07-04T21:04:11Z  Musical Instruments  
670          0.583333  2017-06-29T15:10:58Z  Musical Instruments  
672          0.533333  2017-03-10T16:55:04Z  Musical Instruments  
674          2.000000  2016-10-31T18:10:06Z  Musical Instruments  

[87 rows x 12 columns]

In [108]:
df['level'].value_counts()

level
All Levels            324
Beginner Level        266
Intermediate Level     78
Expert Level           12
Name: count, dtype: int64

In [117]:
df.level == 'All Levels' and df.Rating > 0.5

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [116]:
df.Rating > 0.5

0       True
1       True
2       True
3       True
4      False
       ...  
675    False
676    False
677    False
678     True
679    False
Name: Rating, Length: 680, dtype: bool